---
title: "Titanic EDA"
author: "Martijn van Bloois"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r pkg-load}
library(tidyverse)
library(tidymodels)
library(janitor)
#library(glmnet)
library(rpart.plot) 
```

```{r data-load}
train <- read_csv("./data/train.csv") %>% 
  mutate(Survived = factor(Survived),
         Pclass = factor(Pclass),
         Fare = log1p(Fare),
         Embarked = ifelse(is.na(Embarked), mode(Embarked), Embarked),
         Cabin = ifelse(is.na(Cabin), "no", "yes")
         ) %>% 
  select(Survived, Embarked, Sex, Fare, Pclass, Cabin)

test <- read_csv("./data/test.csv") %>% 
  mutate(Pclass = factor(Pclass),
         Fare = log1p(Fare),
         Embarked = ifelse(is.na(Embarked), mode(Embarked), Embarked),
         Cabin = ifelse(is.na(Cabin), "no", "yes")
         ) %>% 
    select(Embarked, Sex, Fare, Pclass, Cabin)
```


```{r}
model <- decision_tree(
   cost_complexity = tune(),
   tree_depth = tune()
   ) %>% 
  set_engine("rpart") %>% 
  set_mode("classification")

recipe <- recipe(formula = Survived ~ ., data = train) %>% 
  step_dummy(all_nominal_predictors())

tree_grid <- grid_regular(cost_complexity(),
                          tree_depth(),
                          levels = 5)

set.seed(123)
data_split <- initial_split(train, 
                            strata = Survived)
data_train <- training(data_split)
data_test  <- testing(data_split)

set.seed(234)
data_folds <- vfold_cv(data_train)

set.seed(345)

data_wf <- workflow() %>%
  add_model(model) %>%
  add_recipe(recipe)

data_res <- 
  data_wf %>% 
  tune_grid(
    resamples = data_folds,
    grid = tree_grid
    )

data_res

data_res %>% 
  collect_metrics()

data_res %>% 
  collect_metrics() %>%
  mutate(tree_depth = factor(tree_depth)) %>%
  ggplot(aes(cost_complexity, mean, color = tree_depth)) +
  geom_line(size = 1.5, alpha = 0.6) +
  geom_point(size = 2) +
  facet_wrap(~ .metric, scales = "free", nrow = 2) +
  scale_x_log10(labels = scales::label_number()) +
  scale_color_viridis_d(option = "plasma", begin = .9, end = 0)

data_res %>%
  show_best("accuracy")

best_tree <- data_res %>%
  select_best("accuracy")

final_wf <- 
  data_wf %>% 
  finalize_workflow(best_tree)

final_fit <- 
  final_wf %>%
  last_fit(data_split) 

final_fit %>%
  collect_metrics()

final_fit %>%
  collect_predictions() %>% 
  roc_curve(Survived, .pred_class) %>% 
  autoplot()

final_tree <- extract_workflow(final_fit)
final_tree

final_tree %>%
  extract_fit_engine() %>%
  rpart.plot(roundint = FALSE)

library(vip)

final_tree %>% 
  extract_fit_parsnip() %>% 
  vip()
```

