---
title: "Titanic EDA"
author: "Martijn van Bloois"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r pkg-load}
library(tidyverse)
library(janitor)
library(randomForest)
```

```{r data-load}
train <- read_csv("./data/train.csv") %>% 
  mutate(Pclass = factor(Pclass),
         Fare = log1p(Fare),
         Embarked = ifelse(is.na(Embarked), mode(Embarked), Embarked))
test <- read_csv("./data/test.csv") %>% 
  mutate(Pclass = factor(Pclass),
         Fare = log1p(Fare),
         Embarked = ifelse(is.na(Embarked), mode(Embarked), Embarked))
```


```{r}
model <- randomForest(Survived ~ Sex + Pclass + Fare + Embarked, data = train, importance = TRUE, mtry = 6)
summary(model)

probabilities <- predict(model, test, type = "class")

predicted_classes <- ifelse(probabilities > 0.5, 1, 0)

results <- test %>% 
  bind_cols(predicted_classes) %>% 
  select(PassengerId, Survived = ...12)

write_csv(results, "./data/titanic_rF_20220719.csv")
```

